---
- name: Get Device Facts
  hosts: vqfx10k
  roles:
    - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieving information from devices running Junos OS
      juniper_junos_facts:
        host: "{{ ansible_ssh_host }}"
        port: "{{ ansible_ssh_port }}"
        ssh_keyfile: "{{ ansible_ssh_private_key_file }}"
        user: vagrant
      register: result

      #print results to screen
    - name: Print facts
      debug:
        var: result
